# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

In [3]:
from pyexpat import features

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

In [4]:
df = pd.read_csv('phone_addiction.csv', encoding='latin-1')

In [5]:
df = df.dropna(subset=['addiction_level'])

In [6]:
df.head()

,age,daily_screen_time,social_media_hours,study_hours,sleep_hours,notifications_per_day,focus_score,coffee_per_day,breaks_per_day,night_usage,distraction_score,addiction_level,productivity_score
0,21.0,5.95,2.81,2.61,7.377325,290.254742,NaN,2.0,1.0,0.0,7.852,Medium,29.587834
1,34.0,3.82,2.33,0.28,7.612689,270.571074,93.65,1.0,3.0,0.0,7.146,Medium,17.320665
2,29.0,3.57,1.64,5.21,6.143298,134.054219,100.00,0.0,5.0,0.0,2.962,Low,75.183980
3,25.0,10.27,4.37,4.28,4.012145,233.019834,94.71,2.0,2.0,1.0,8.791,Medium,31.133161
4,22.0,2.42,1.60,3.67,6.953253,19.381791,100.00,0.0,3.0,0.0,0.669,Low,54.640676

In [7]:
df = df.drop(columns=['age'])

In [8]:
target_column = 'addiction_level'

In [9]:
X = df.drop(columns=[target_column])
y = df[target_column]

In [10]:
X

,daily_screen_time,social_media_hours,study_hours,sleep_hours,notifications_per_day,focus_score,coffee_per_day,breaks_per_day,night_usage,distraction_score,productivity_score
0,5.950000,2.810000,2.610000,7.377325,290.254742,NaN,2.000000,1.000000,0.0,7.852000,29.587834
1,3.820000,2.330000,0.280000,7.612689,270.571074,93.650000,1.000000,3.000000,0.0,7.146000,17.320665
2,3.570000,1.640000,5.210000,6.143298,134.054219,100.000000,0.000000,5.000000,0.0,2.962000,75.183980
3,10.270000,4.370000,4.280000,4.012145,233.019834,94.710000,2.000000,2.000000,1.0,8.791000,31.133161
4,2.420000,1.600000,3.670000,6.953253,19.381791,100.000000,0.000000,3.000000,0.0,0.669000,54.640676
...,...,...,...,...,...,...,...,...,...,...,...
9994,7.891137,4.147632,2.791273,5.312900,79.980390,NaN,0.956262,2.171888,1.0,4.941907,27.983952
9996,5.436996,2.720247,3.108437,NaN,255.577384,95.524177,0.000000,3.760062,0.0,5.611804,35.429210
9997,8.902568,5.699933,2.144991,9.005448,283.669947,88.652853,1.618292,4.379232,1.0,8.632106,0.000000
9998,8.810238,5.042961,0.746631,8.270466,197.836399,93.355528,1.225703,0.331569,1.0,6.031921,36.117423
9999,8.538017,3.684197,2.361045,8.725604,90.687644,100.000000,1.450320,1.534101,1.0,2.923829,58.035377

In [11]:
y

0       Medium
1       Medium
2          Low
3       Medium
4          Low
         ...
9994    Medium
9996       Low
9997      High
9998    Medium
9999    Medium
Name: addiction_level, Length: 9517, dtype: str

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (9517, 11)
y shape: (9517,)

In [14]:
imputer = SimpleImputer(strategy='mean')

X_train_clean = imputer.fit_transform(X_train)
X_test_clean = imputer.transform(X_test)